### ISSUE TITLE
how to pull the submodules codes?

### ISSUE THREAD

**Issue by laris** [owskio/avrAsmExamples#1]
not upload?

Thanks and hope to pull down to learn

**Comment by owskio** [comment]
Crap, sorry Laris, looks like Git needs a trailing slash when saving programs:
https://stackoverflow.com/questions/28384464/why-can-i-not-open-my-folder-in-github/33012796
I was really just using github to save, 
I wasn't thinking about sharing,
I may not even have this code anymore then,
I'll have to check the original machine when I get home from work.

**Comment by owskio** [comment]
In the mean time, 
It appears I was prescient enough to post most of those examples,
under my Gists, here:
https://gist.github.com/owskio

**Comment by owskio** [comment]
In the mean time, 
It appears I was prescient enough to post most of those examples,
under my Gists, here:
https://gist.github.com/owskio

**Comment by owskio** [comment]
Found the code years later lol, un-sub-moduled

**Comment by laris** [comment]
Thank you owskio!
